"""initial schema

Revision ID: 4401e8f1aa5a
Revises: 
Create Date: 2026-07-20 13:52:33.838583
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4401e8f1aa5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('external_provider_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('home_team', sa.String(length=120), nullable=False),
    sa.Column('away_team', sa.String(length=120), nullable=False),
    sa.Column('xg_home', sa.Float(), nullable=False),
    sa.Column('xg_away', sa.Float(), nullable=False),
    sa.Column('prob_home', sa.Float(), nullable=False),
    sa.Column('prob_draw', sa.Float(), nullable=False),
    sa.Column('prob_away', sa.Float(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('provider_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_created_at'), ['created_at'], unique=False)

    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider_type', sa.String(length=60), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('auth_header', sa.String(length=120), nullable=False),
    sa.Column('encrypted_api_key', sa.String(length=512), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('external_provider_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_provider_id', name='uq_team_external')
    )
    op.create_table('api_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_logs_provider_id'), ['provider_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_created_at'))

    op.drop_table('api_usage_logs')
    op.drop_table('teams')
    op.drop_table('providers')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_created_at'))

    op.drop_table('predictions')
    op.drop_table('leagues')
    # ### end Alembic commands ###
