"""provider weight

Revision ID: 4b43ac5a8ebe
Revises: 8e45b0973ac6
Create Date: 2026-08-05 20:15:25.837313
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b43ac5a8ebe'
down_revision: Union[str, None] = '8e45b0973ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False, server_default='1.0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
